#!/bin/bash

# Configure shared config dir
XDG_CONFIG_HOME="$HOME/.config"
mkdir -p "$XDG_CONFIG_HOME"

# Set up symlinks
ln -nfs "$(pwd)/ruby/.gemrc"            "$HOME/.gemrc"
ln -nfs "$(pwd)/ruby/.irbrc"            "$HOME/.irbrc"

ln -nfs "$(pwd)/zsh/.zshrc"             "$HOME/.zshrc"
ln -nfs "$(pwd)/zsh/.zsh"               "$HOME/.zsh"
ln -nfs "$(pwd)/.ruby-version"          "$HOME/.ruby-version"
mkdir -p "$HOME/.bundle"
ln -nfs "$(pwd)/ruby/bundle/config" "$HOME/.bundle/config"

mkdir -p "$HOME/.bin"
ln -nfs "$(pwd)/bin/git-fixup" "$HOME/.bin/git-fixup"

ln -nfs "$(pwd)/vim/.vimrc"             "$HOME/.vimrc"
ln -nfs "$(pwd)/vim/.gvimrc"            "$HOME/.gvimrc"
ln -nfs "$(pwd)/vim/.vim"               "$HOME/.vim"
ln -nfs "$(pwd)/vim/.vim"               "$XDG_CONFIG_HOME/nvim"
ln -nfs "$(pwd)/hammerspoon"            "$HOME/.hammerspoon"

ln -nfs "$(pwd)/.ignore_global" "$HOME/.ignore"
mkdir -p "$XDG_CONFIG_HOME/git"
ln -nfs "$(pwd)/git/.gitignore_global" "$XDG_CONFIG_HOME/git/.gitignore_global"
mkdir -p "$XDG_CONFIG_HOME/tig"
ln -nfs "$(pwd)/git/.tigrc" "$XDG_CONFIG_HOME/tig/config"
ln -nfs "$HOME/Dropbox/vim/spell" "$HOME/.vim/spell"
mkdir -p "$HOME/.VIM_UNDO_FILES"

mkdir -p "$HOME/.gnupg"
ln -nfs "$(pwd)/.gnupg/gpg.conf" "$HOME/.gnupg/gpg.conf"
ln -nfs "$(pwd)/.gnupg/gpg-agent.conf" "$HOME/.gnupg/gpg-agent.conf"

mkdir -p "$HOME/.ctags.d"
ln -nfs "$(pwd)/config.ctags" "$HOME/.ctags.d/config.ctags"

# Copy powerlines
for file in ./powerline-fonts/Meslo/*.otf; do
  cp -f "$file" "$HOME/Library/Fonts/"
done

# https://github.com/postmodern/chruby/issues/196#issuecomment-23826171
[[ -e /etc/zshenv ]] && sudo mv /etc/zshenv /etc/zprofile

git config --global user.email "tom@tomdebruijn.com"
git config --global user.name "Tom de Bruijn"
git config --global core.excludesfile "$HOME/.gitignore_global"
git config --global color.diff always
git config --global merge.ff only
git config --global push.default current
git config --global remote.origin.prune true
git config --global merge.conflictstyle diff3
# Override default git commit message comment symbol.
# This allows me to use the default comment symbol (#) at the beginning of a
# line instead. Useful for when used in code examples.
# see @gitCommitMessage
git config --global core.commentChar ";"

if [ -n "$GPG_SIGNING_KEY" ]; then
  git config --global user.signingkey $GPG_SIGNING_KEY
  git config --global commit.gpgsign true
else
  echo "WARNING: Git GPG configuration skipped. No \$GPG_SIGNING_KEY found."
fi
