#!/bin/bash

# Configure shared config dir
XDG_CONFIG_HOME="$HOME/.config"
mkdir -p "$XDG_CONFIG_HOME"

# Set up symlinks
ln -nfs "$(pwd)/ruby/.gemrc"            "$HOME/.gemrc"
ln -nfs "$(pwd)/ruby/.irbrc"            "$HOME/.irbrc"

ln -nfs "$(pwd)/zsh/.zshrc"             "$HOME/.zshrc"
ln -nfs "$(pwd)/zsh/.zshenv"            "$HOME/.zshenv"
ln -nfs "$(pwd)/zsh/.zprofile"          "$HOME/.zprofile"
ln -nfs "$(pwd)/zsh/.zsh"               "$HOME/.zsh"
ln -nfs "$(pwd)/.ruby-version"          "$HOME/.ruby-version"
mkdir -p "$HOME/.bundle"
ln -nfs "$(pwd)/ruby/bundle/config" "$HOME/.bundle/config"

mkdir -p "$HOME/.bin"
ln -nfs "$(pwd)/bin/git-fixup" "$HOME/.bin/git-fixup"
ln -nfs "$(pwd)/bin/retry" "$HOME/.bin/retry"
ln -nfs "$(pwd)/bin/solargraph_wrapper" "$HOME/.bin/solargraph_wrapper"

ln -nfs "$(pwd)/vim/.vimrc"             "$HOME/.vimrc"
ln -nfs "$(pwd)/vim/.gvimrc"            "$HOME/.gvimrc"
ln -nfs "$(pwd)/vim/.vim"               "$HOME/.vim"
ln -nfs "$(pwd)/nvim"                   "$XDG_CONFIG_HOME/nvim"
ln -nfs "$(pwd)/cloc/"                  "$XDG_CONFIG_HOME/cloc"
ln -nfs "$(pwd)/hammerspoon"            "$HOME/.hammerspoon"

ln -nfs "$(pwd)/.ignore_global" "$HOME/.ignore"
mkdir -p "$XDG_CONFIG_HOME/git"
ln -nfs "$(pwd)/git/.gitignore_global" "$XDG_CONFIG_HOME/git/.gitignore_global"
ln -nfs "$(pwd)/git/.gitattributes_global" "$XDG_CONFIG_HOME/git/.gitattributes_global"
mkdir -p "$XDG_CONFIG_HOME/tig"
ln -nfs "$(pwd)/git/.tigrc" "$XDG_CONFIG_HOME/tig/config"
mkdir -p "$XDG_CONFIG_HOME/alacritty"
ln -nfs "$(pwd)/alacritty/alacritty.toml" "$XDG_CONFIG_HOME/alacritty/alacritty.toml"
mkdir -p "$XDG_CONFIG_HOME/zellij"
ln -nfs "$(pwd)/zellij/config.kdl" "$XDG_CONFIG_HOME/zellij/config.kdl"
ln -nfs "$(pwd)/zellij/layouts" "$XDG_CONFIG_HOME/zellij/layouts"
mkdir -p "$XDG_CONFIG_HOME/ripgrep"
ln -nfs "$(pwd)/.ripgreprc" "$XDG_CONFIG_HOME/ripgrep/.ripgreprc"
mkdir -p "$XDG_CONFIG_HOME/bat"
ln -nfs "$(pwd)/bat/config" "$XDG_CONFIG_HOME/bat/config"
ln -nfs "$HOME/Library/Mobile Documents/com~apple~CloudDocs/vim/vim/spell" "$HOME/.vim/spell"
ln -nfs "$HOME/Library/Mobile Documents/com~apple~CloudDocs/vim/neovim/spell" "$HOME/.local/share/nvim/spell"
ln -nfs "$HOME/Library/Mobile Documents/com~apple~CloudDocs/vim/harper-ls/dictionary.txt" "$XDG_CONFIG_HOME/harper-ls/dictionary.txt"
mkdir -p "$HOME/.VIM_UNDO_FILES"

mkdir -p "$HOME/.gnupg"
ln -nfs "$(pwd)/.gnupg/gpg.conf" "$HOME/.gnupg/gpg.conf"
ln -nfs "$(pwd)/.gnupg/gpg-agent.conf" "$HOME/.gnupg/gpg-agent.conf"

mkdir -p "$HOME/.ctags.d"
ln -nfs "$(pwd)/config.ctags" "$HOME/.ctags.d/config.ctags"

# Silence login message on Shell start
touch "$HOME"/.hushlogin

# Copy powerlines
for file in ./powerline-fonts/Meslo/*.otf; do
  cp -f "$file" "$HOME/Library/Fonts/"
done

git config --global include.path "$(pwd)/git/extra.gitconfig"

if [ -n "$GPG_SIGNING_KEY" ]; then
  git config --global user.signingkey "$GPG_SIGNING_KEY"
  git config --global commit.gpgsign true
else
  echo "WARNING: Git GPG configuration skipped. No \$GPG_SIGNING_KEY found."
fi

# Make MacVim window title bar dark
defaults write org.vim.MacVim MMTitlebarAppearsTransparent true
